version: 1.0.{build}
image: Visual Studio 2017
services: mssql2017
branches:
  only:
  - toolChain
environment:
  secret: 
    secure: 0W65ZoMAe2gV9n68FqTY/Q==
  SqlServer/MasterConnectionString: Server=(local)\SQL2016;Database=master;User ID=sa;Password=Password12!
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
