version: 1.0.{build}
image: Visual Studio 2017
services: mssql2017
branches:
  only:
  - toolChain
environment:
  secret: 
    secure: 0W65ZoMAe2gV9n68FqTY/Q==
  SqlServer/MasterConnectionString: Server=(local)\SQL2016;Database=master;User ID=sa;Password=Password12!
init:
  - ps: git config --global core.autocrlf input
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt C:\projects\in-Projects\inProjects.WebApp\appsettings.json.enc -secret %secret%
  - cmd: appveyor-tools\secure-file -decrypt C:\projects\in-Projects\inProjects.WebApp\appsettings.Development.json.enc -secret %secret%
build_script:
  - dotnet run --project CodeCakeBuilder -autointeraction -PublishDirtyRepo=Y -RunUnitTests=Y