[name]
# une chaine de caractere.
project_name = "PFH Test"

[semester]
# un entier positif représentant votre semestre.
semester = 4
# La chaine de caractere "SR" ou "IL" pour votre filière Systemes et Réseaux ou Ingénieurie Logiciel "None" si vous êtes en semestre 1 ou 2.
sector = "None"

[background]
# L'URL publique de votre image de fond.
image = "https://mon_image_de_background.png"

[logo]
# L'URL publique de votre logo.
url = "https://drive.google.com/open?id=1fOM-KXLRH6IZJORaZFHawh7TQXvehylT"

[slogan]
# Une chaine de caractere.
slogan = "ARTTTTT"

[pitch]
# Une chaine de caractere.
pitch = "Vous avez des problemes ? Notre super project est là pour vous !"

[team]
# L'e-mail du chef de projet, "None" si vous n'en avez pas.
leader = "agopian@intechinfo.fr"
# La liste d'e-mail des membres de votre projet. Ne remettez pas le chef de projet s'il est précisé.
members = ["chiche@intechinfo.fr","acheng@intechinfo.fr"]
